### ISSUE TITLE
Bottom right panel becomes unusable

### ISSUE THREAD

**Issue by jelmerderonde** [cognitect-labs/REBL-distro#21]
Often when using REBL I get the following stacktrace:

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
    at javafx.scene.control.skin.TableCellSkin.tableColumnProperty(TableCellSkin.java:97)
    at javafx.scene.control.skin.TableCellSkinBase.getTableColumn(TableCellSkinBase.java:123)
    at javafx.scene.control.skin.TableCellSkinBase.dispose(TableCellSkinBase.java:136)
    at javafx.scene.control.skin.TableCellSkin.dispose(TableCellSkin.java:88)
    at javafx.scene.control.Control$2.invalidated(Control.java:267)
    at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
    at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
    at javafx.css.StyleableObjectProperty.set(StyleableObjectProperty.java:82)
    at javafx.scene.control.Control$2.set(Control.java:250)
    at javafx.scene.control.Control$2.set(Control.java:233)
    at javafx.scene.control.Control.setSkin(Control.java:230)
    at javafx.scene.control.skin.TableRowSkinBase.recreateCells(TableRowSkinBase.java:715)
    at javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:505)
    at javafx.scene.control.skin.TableRowSkinBase.checkState(TableRowSkinBase.java:649)
    at javafx.scene.control.skin.TableRowSkinBase.computePrefHeight(TableRowSkinBase.java:588)
    at javafx.scene.control.Control.computePrefHeight(Control.java:570)
    at javafx.scene.Parent.prefHeight(Parent.java:1037)
    at javafx.scene.layout.Region.prefHeight(Region.java:1559)
    at javafx.scene.control.skin.VirtualFlow.resizeCellSize(VirtualFlow.java:1863)
    at javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:2043)
    at javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1253)
    at javafx.scene.control.skin.VirtualFlow$5.invalidated(VirtualFlow.java:837)
    at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
    at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
    at javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:855)
    at javafx.scene.control.skin.TableViewSkinBase.updateItemCount(TableViewSkinBase.java:549)
    at javafx.scene.control.skin.VirtualContainerBase.checkState(VirtualContainerBase.java:170)
    at javafx.scene.control.skin.VirtualContainerBase.layoutChildren(VirtualContainerBase.java:145)
    at javafx.scene.control.skin.TableViewSkinBase.layoutChildren(TableViewSkinBase.java:407)
    at javafx.scene.control.Control.layoutChildren(Control.java:601)
    at javafx.scene.Parent.layout(Parent.java:1204)
    at javafx.scene.Parent.layout(Parent.java:1211)
    at javafx.scene.Parent.layout(Parent.java:1211)
    at javafx.scene.Parent.layout(Parent.java:1211)
    at javafx.scene.Parent.layout(Parent.java:1211)
    at javafx.scene.Parent.layout(Parent.java:1211)
    at javafx.scene.Parent.layout(Parent.java:1211)
    at javafx.scene.Parent.layout(Parent.java:1211)
    at javafx.scene.Scene.doLayoutPass(Scene.java:576)
    at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)
    at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

After this, the bottom right panel of REBL is no longer usable: it either resizes to 0x0/hides/or something else, but I can no longer read the contents.

deps.edn:
```
:rebl {:extra-deps {com.cognitect/rebl              {:local/root "/Users/jelmer/bin/REBL-0.9.149.jar"}
                               org.clojure/core.async        {:mvn/version "0.4.490"}
                               org.openjfx/javafx-fxml       {:mvn/version "11.0.2"}
                               org.openjfx/javafx-controls {:mvn/version "11.0.2"}
                               org.openjfx/javafx-swing     {:mvn/version "11.0.2"}
                               org.openjfx/javafx-base       {:mvn/version "11.0.2"}
                               org.openjfx/javafx-web        {:mvn/version "11.0.2"}}
           :main-opts  ["-m" "cognitect.rebl"]}}}
```

Java version:
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

**Comment by jelmerderonde** [comment]
I've done some more testing, since the problem has become worse after upgrading to rebl 0.9.168. Now the following stacktrace occurs whenever I eval a collection of some sort: lists, vectors, maps, etc.

```
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/jmx/MXNodeAlgorithm
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3192)
	at java.base/java.lang.Class.getMethods(Class.java:1905)
	at clojure.lang.Reflector.getMethods(Reflector.java:498)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:98)
	at cognitect.rebl.fx$cell_callback$reify__11975$fn__11976.invoke(fx.clj:255)
	at cognitect.rebl.fx.proxy$javafx.scene.control.TableCell$ff19274a.updateItem(Unknown Source)
	at javafx.scene.control.TableCell.updateItem(TableCell.java:665)
	at javafx.scene.control.TableCell.indexChanged(TableCell.java:469)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
	at cognitect.rebl.fx.proxy$javafx.scene.control.TableCell$ff19274a.updateIndex(Unknown Source)
	at javafx.scene.control.skin.TableSkinUtils.resizeColumnToFitContent(TableSkinUtils.java:119)
	at javafx.scene.control.skin.TableSkinUtils.resizeColumnToFitContent(TableSkinUtils.java:86)
	at javafx.scene.control.skin.TableColumnHeader.doColumnAutoSize(TableColumnHeader.java:573)
	at javafx.scene.control.skin.TableColumnHeader.updateScene(TableColumnHeader.java:516)
	at javafx.scene.control.skin.TableColumnHeader.lambda$new$0(TableColumnHeader.java:159)
	at com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(LambdaMultiplePropertyChangeListenerHandler.java:49)
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:86)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1054)
	at javafx.scene.Node.invalidatedScenes(Node.java:1114)
	at javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.scene.Parent$2.onChanged(Parent.java:369)
	at com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
	at javafx.scene.control.skin.NestedTableColumnHeader.updateContent(NestedTableColumnHeader.java:578)
	at javafx.scene.control.skin.NestedTableColumnHeader.updateTableColumnHeaders(NestedTableColumnHeader.java:504)
	at javafx.scene.control.skin.NestedTableColumnHeader.checkState(NestedTableColumnHeader.java:638)
	at javafx.scene.control.skin.NestedTableColumnHeader.computePrefHeight(NestedTableColumnHeader.java:345)
	at javafx.scene.Parent.prefHeight(Parent.java:1031)
	at javafx.scene.layout.Region.prefHeight(Region.java:1559)
	at javafx.scene.control.skin.TableHeaderRow.computePrefHeight(TableHeaderRow.java:376)
	at javafx.scene.control.skin.TableHeaderRow.computeMinHeight(TableHeaderRow.java:369)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.control.SkinBase.computeMinHeight(SkinBase.java:311)
	at javafx.scene.control.Control.computeMinHeight(Control.java:512)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1915)
	at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:2196)
	at javafx.scene.layout.Region.computeMaxMinAreaHeight(Region.java:2069)
	at javafx.scene.layout.StackPane.computeMinHeight(StackPane.java:295)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1915)
	at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:2196)
	at javafx.scene.layout.Region.computeMaxMinAreaHeight(Region.java:2069)
	at javafx.scene.layout.StackPane.computeMinHeight(StackPane.java:295)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.control.skin.SplitPaneSkin.computeMinHeight(SplitPaneSkin.java:440)
	at javafx.scene.control.Control.computeMinHeight(Control.java:512)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1915)
	at javafx.scene.layout.VBox.getAreaHeights(VBox.java:446)
	at javafx.scene.layout.VBox.computeContentHeight(VBox.java:528)
	at javafx.scene.layout.VBox.computeMinHeight(VBox.java:406)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1915)
	at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:2196)
	at javafx.scene.layout.Region.computeMaxMinAreaHeight(Region.java:2069)
	at javafx.scene.layout.StackPane.computeMinHeight(StackPane.java:295)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.control.skin.SplitPaneSkin.computeMinHeight(SplitPaneSkin.java:440)
	at javafx.scene.control.Control.computeMinHeight(Control.java:512)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.layout.Region.computeChildPrefAreaHeight(Region.java:1980)
	at javafx.scene.layout.VBox.getAreaHeights(VBox.java:450)
	at javafx.scene.layout.VBox.layoutChildren(VBox.java:561)
	at javafx.scene.Parent.layout(Parent.java:1204)
	at javafx.scene.Scene.doLayoutPass(Scene.java:576)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.jmx.MXNodeAlgorithm
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 97 more
```

Code I used to test:
```clojure
(ns rebl-test.core)

(comment
  ; I use this to create a fresh ui that works. So I don'(try
  ; have to restart the repl every time the problem occurs.
  (cognitect.rebl/ui)
  nil)

; These work fine
(do 1)
(do 1M)
(do 2/3)
(do \a)
(do 'symbol)
(do :keyword)
(do "string")
(do nil)

; These trigger the error
(do '(:a :b :c))
(do [1 2 3])
(do {:a-key "a val"})
(do #{:a :b})
```

deps.edn:
```clojure
{:aliases {:rebl {:extra-deps {org.clojure/clojure         {:mvn/version "1.10.0"}
                               com.cognitect/rebl          {:local/root "/Users/jelmer/bin/REBL-0.9.168.jar"}
                               org.clojure/core.async      {:mvn/version "0.4.490"}
                               org.openjfx/javafx-fxml     {:mvn/version "11.0.1"}
                               org.openjfx/javafx-controls {:mvn/version "11.0.1"}
                               org.openjfx/javafx-swing    {:mvn/version "11.0.1"}
                               org.openjfx/javafx-base     {:mvn/version "11.0.1"}
                               org.openjfx/javafx-web      {:mvn/version "11.0.1"}}
                  :main-opts  ["-m" "cognitect.rebl"]}}
```

Java version:
java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)

Also, I'm using the Atom Chlorine editor: https://github.com/mauricioszabo/atom-chlorine.
The code to eval and send to rebl is I think here: https://github.com/mauricioszabo/atom-chlorine/blob/master/src/chlorine/repl.cljs

**Comment by seancorfield** [comment]
I see this happening with openjfx 11.0.2 and 14.0.1 as well. I can reproduce it fairly reliably but it's not a simple set of steps -- it's more to do with how _fast_ you perform certain steps it seems.

1. Fire up REBL
2. `(require '[clojure.reflect :as r])`
3. `(r/reflect {:a 1})`
4. Switch to the browse pane
5. Navigate right as far as you can (five times, should get you to `nil`)
6. Navigate left twice
7. Repeatedly navigate right and then left
8. If you do that often enough and/or fast enough it should trigger the stacktrace
9. At that point the bottom right pane will either be blank or show the value in a smaller area, with blank grey space below and to the right -- and REBL never fully recovers so you have to restart the UI.

**Comment by jelmerderonde** [comment]
@seancorfield , great that you've managed to find the steps to reproduce the issue. To me it always seemed sort of random.

**Comment by puredanger** [comment]
Seems like this is https://bugs.openjdk.java.net/browse/JDK-8217953
Reported fixed in https://bugs.openjdk.java.net/browse/JDK-8244112 recently for javafx15 (don't see backport)

**Comment by seancorfield** [comment]
I just tried OpenJFX 15 early access 6 and I can no longer repro this:
```clojure
                org.openjfx/javafx-fxml     {:mvn/version "15-ea+6"}
                org.openjfx/javafx-controls {:mvn/version "15-ea+6"}
                org.openjfx/javafx-graphics {:mvn/version "15-ea+6"}
                org.openjfx/javafx-media    {:mvn/version "15-ea+6"}
                org.openjfx/javafx-swing    {:mvn/version "15-ea+6"}
                org.openjfx/javafx-base     {:mvn/version "15-ea+6"}
                org.openjfx/javafx-web      {:mvn/version "15-ea+6"}
```

**Comment by jelmerderonde** [comment]
Thanks for this @puredanger! After changing my javafx dependencies the bug no longer occurs. I think this can be closed?

**Comment by puredanger** [comment]
Thanks! We are working on a release with updated deps and I'll close it when that's out.

**Comment by puredanger** [comment]
REBL 0.9.226 provides pre-built deps.edn files that pull in OpenJavaFX 15-ea6 - see https://github.com/cognitect-labs/REBL-distro#usage for more details.
