### ISSUE TITLE
Exception occurs when evaling collections.

### ISSUE THREAD

**Issue by jelmerderonde** [cognitect-labs/REBL-distro#29]
The following stacktrace occurs whenever I eval a collection of some sort: lists, vectors, maps, etc. Also, the REBL ui becomes unusable: the lower right bottom of the ui no longer shows any results and navigating (ctr+<, ctr+>) no longer works.

```
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/jmx/MXNodeAlgorithm
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3192)
	at java.base/java.lang.Class.getMethods(Class.java:1905)
	at clojure.lang.Reflector.getMethods(Reflector.java:498)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:98)
	at cognitect.rebl.fx$cell_callback$reify__11975$fn__11976.invoke(fx.clj:255)
	at cognitect.rebl.fx.proxy$javafx.scene.control.TableCell$ff19274a.updateItem(Unknown Source)
	at javafx.scene.control.TableCell.updateItem(TableCell.java:665)
	at javafx.scene.control.TableCell.indexChanged(TableCell.java:469)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
	at cognitect.rebl.fx.proxy$javafx.scene.control.TableCell$ff19274a.updateIndex(Unknown Source)
	at javafx.scene.control.skin.TableSkinUtils.resizeColumnToFitContent(TableSkinUtils.java:119)
	at javafx.scene.control.skin.TableSkinUtils.resizeColumnToFitContent(TableSkinUtils.java:86)
	at javafx.scene.control.skin.TableColumnHeader.doColumnAutoSize(TableColumnHeader.java:573)
	at javafx.scene.control.skin.TableColumnHeader.updateScene(TableColumnHeader.java:516)
	at javafx.scene.control.skin.TableColumnHeader.lambda$new$0(TableColumnHeader.java:159)
	at com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(LambdaMultiplePropertyChangeListenerHandler.java:49)
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:86)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1054)
	at javafx.scene.Node.invalidatedScenes(Node.java:1114)
	at javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.scene.Parent$2.onChanged(Parent.java:369)
	at com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
	at javafx.scene.control.skin.NestedTableColumnHeader.updateContent(NestedTableColumnHeader.java:578)
	at javafx.scene.control.skin.NestedTableColumnHeader.updateTableColumnHeaders(NestedTableColumnHeader.java:504)
	at javafx.scene.control.skin.NestedTableColumnHeader.checkState(NestedTableColumnHeader.java:638)
	at javafx.scene.control.skin.NestedTableColumnHeader.computePrefHeight(NestedTableColumnHeader.java:345)
	at javafx.scene.Parent.prefHeight(Parent.java:1031)
	at javafx.scene.layout.Region.prefHeight(Region.java:1559)
	at javafx.scene.control.skin.TableHeaderRow.computePrefHeight(TableHeaderRow.java:376)
	at javafx.scene.control.skin.TableHeaderRow.computeMinHeight(TableHeaderRow.java:369)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.control.SkinBase.computeMinHeight(SkinBase.java:311)
	at javafx.scene.control.Control.computeMinHeight(Control.java:512)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1915)
	at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:2196)
	at javafx.scene.layout.Region.computeMaxMinAreaHeight(Region.java:2069)
	at javafx.scene.layout.StackPane.computeMinHeight(StackPane.java:295)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1915)
	at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:2196)
	at javafx.scene.layout.Region.computeMaxMinAreaHeight(Region.java:2069)
	at javafx.scene.layout.StackPane.computeMinHeight(StackPane.java:295)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.control.skin.SplitPaneSkin.computeMinHeight(SplitPaneSkin.java:440)
	at javafx.scene.control.Control.computeMinHeight(Control.java:512)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1915)
	at javafx.scene.layout.VBox.getAreaHeights(VBox.java:446)
	at javafx.scene.layout.VBox.computeContentHeight(VBox.java:528)
	at javafx.scene.layout.VBox.computeMinHeight(VBox.java:406)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1915)
	at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:2196)
	at javafx.scene.layout.Region.computeMaxMinAreaHeight(Region.java:2069)
	at javafx.scene.layout.StackPane.computeMinHeight(StackPane.java:295)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.control.skin.SplitPaneSkin.computeMinHeight(SplitPaneSkin.java:440)
	at javafx.scene.control.Control.computeMinHeight(Control.java:512)
	at javafx.scene.Parent.minHeight(Parent.java:1059)
	at javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.scene.layout.Region.computeChildPrefAreaHeight(Region.java:1980)
	at javafx.scene.layout.VBox.getAreaHeights(VBox.java:450)
	at javafx.scene.layout.VBox.layoutChildren(VBox.java:561)
	at javafx.scene.Parent.layout(Parent.java:1204)
	at javafx.scene.Scene.doLayoutPass(Scene.java:576)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.jmx.MXNodeAlgorithm
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 97 more
```

Code I used to test:

```clojure
(ns rebl-test.core)

(comment
  ; I use this to create a fresh ui that works. So I don'(try
  ; have to restart the repl every time the problem occurs.
  (cognitect.rebl/ui)
  nil)

; These work fine
(do 1)
(do 1M)
(do 2/3)
(do \a)
(do 'symbol)
(do :keyword)
(do "string")
(do nil)

; These trigger the error
(do '(:a :b :c))
(do [1 2 3])
(do {:a-key "a val"})
(do #{:a :b})
```

deps.edn:
```clojure
{:aliases {:rebl {:extra-deps {org.clojure/clojure         {:mvn/version "1.10.0"}
                               com.cognitect/rebl          {:local/root "/Users/jelmer/bin/REBL-0.9.168.jar"}
                               org.clojure/core.async      {:mvn/version "0.4.490"}
                               org.openjfx/javafx-fxml     {:mvn/version "11.0.1"}
                               org.openjfx/javafx-controls {:mvn/version "11.0.1"}
                               org.openjfx/javafx-swing    {:mvn/version "11.0.1"}
                               org.openjfx/javafx-base     {:mvn/version "11.0.1"}
                               org.openjfx/javafx-web      {:mvn/version "11.0.1"}}
                  :main-opts  ["-m" "cognitect.rebl"]}}
```
REBL version: rebl 0.9.168.

Java version:
java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)

Also, I'm using the Atom Chlorine editor: https://github.com/mauricioszabo/atom-chlorine.
The code to eval and send to rebl is I think here: https://github.com/mauricioszabo/atom-chlorine/blob/master/src/chlorine/repl.cljs

**Comment by seancorfield** [comment]
This should be fixed in the latest REBL @jelmerderonde -- can you confirm?

**Comment by jelmerderonde** [comment]
Yes I can confirm that it works now. Thanks!
