### ISSUE TITLE
FileNotFoundException: Could not locate cljfmt/core__init.class

### ISSUE THREAD

**Issue by didibus** [cognitect-labs/REBL-distro#34]
I'm trying to get it to work from Lein, and even though I have:

```
[org.clojure/clojure "1.10.1"]
[com.cognitect/REBL "0.9.218"]
[org.clojure/core.async "0.4.490"]
```

As dependencies, which are the ones listed on the REBL readme, I get the following error:

```
Caused by: java.io.FileNotFoundException: Could not locate cljfmt/core__init.class, cljfmt/core.clj or cljfmt/core.cljc on classpath.
        at clojure.lang.RT.load(RT.java:466)
        at clojure.lang.RT.load(RT.java:428)
        at clojure.core$load$fn__6824.invoke(core.clj:6126)
        at clojure.core$load.invokeStatic(core.clj:6125)
        at clojure.core$load.doInvoke(core.clj:6109)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5908)
        at clojure.core$load_one.invoke(core.clj:5903)
        at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
        at clojure.core$load_lib.invokeStatic(core.clj:5947)
        at clojure.core$load_lib.doInvoke(core.clj:5928)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$load_libs.invokeStatic(core.clj:5985)
        at clojure.core$load_libs.doInvoke(core.clj:5969)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$require.invokeStatic(core.clj:6007)
        at clojure.core$require.doInvoke(core.clj:6007)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at cognitect.rebl.impl.monaco$loading__6706__auto____15422.invoke(monaco.clj:3)
        at cognitect.rebl.impl.monaco__init.load(Unknown Source)
        at cognitect.rebl.impl.monaco__init.<clinit>(Unknown Source)
```

Which seems to me like monaco has a dependency on cljfmt, should that be listed as well?

**Comment by didibus** [comment]
Adding: `[cljfmt "0.6.4"]` as a dependency fixed this by the way:

```
:dependencies [[org.clojure/clojure "1.10.1"]
                       [com.cognitect/REBL "0.9.218"]
                       [org.clojure/core.async "0.4.490"]
                       [cljfmt "0.6.4"]]
```

**Comment by seancorfield** [comment]
I ran into this and it was due to stale dependencies.

**Comment by didibus** [comment]
How do you fix that? Do a clean?

**Comment by seancorfield** [comment]
Use `-Sforce` with `clj`/`clojure` or just delete the `.cpcache` folder.

**Comment by puredanger** [comment]
cljfmt is a dep, and should be found as a dep of the REBL jar itself (by reading the embedded pom). Seems like there is nothing that needs to be done here though.

Local deps are a little tricky b/c changes in their deps are not automatically detected so an -Sforce is required if they change (and there have been some changes re cljfmt over older releases).
